export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_FULLFILLED = "LOGIN_FULLFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const LOGOUT_FETCHING = "LOGOUT_FETCHING";
export const LOGOUT_FULLFILLED = "LOGOUT_FULLFILLED";
export const LOGOUT_REJECTED = "LOGOUT_REJECTED";