export const FETCH_RESOURCE_BEGIN = "BOILER_FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "BOILER_FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "BOILER_FETCH_RESOURCE_FAILURE";
export const FORM_UPDATE_FIELD = "BOILER_FORM_UPDATE_FIELD";
export const FORM_SUBMIT_BEGIN = "BOILER_FORM_SUBMIT_BEGIN";
export const FORM_SUBMIT_SUCCESS = "BOILER_FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_FAILURE = "BOILER_FORM_SUBMIT_FAILURE";
export const FETCH_RESOURCE_CLEAR_FIELDS =
  "BOILER_FETCH_RESOURCE_CLEAR_FIELDS";