export const FETCH_RESOURCE_BEGIN = "CUSTOMER_FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "CUSTOMER_FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "CUSTOMER_FETCH_RESOURCE_FAILURE";
export const FORM_UPDATE_FIELD = "CUSTOMER_FORM_UPDATE_FIELD";
export const FORM_SUBMIT_BEGIN = "CUSTOMER_FORM_SUBMIT_BEGIN";
export const FORM_SUBMIT_SUCCESS = "CUSTOMER_FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_FAILURE = "CUSTOMER_FORM_SUBMIT_FAILURE";