export const FETCH_RESOURCE_BEGIN = "SCHEDULE_FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "SCHEDULE_FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "SCHEDULE_FETCH_RESOURCE_FAILURE";
export const FORM_SUBMIT_BEGIN = "SCHEDULE_FORM_SUBMIT_BEGIN";
export const FORM_SUBMIT_SUCCESS = "SCHEDULE_FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_FAILURE = "SCHEDULE_FORM_SUBMIT_FAILURE";
export const FETCH_RESOURCE_CLEAR_FIELDS = "SCHEDULE_FETCH_RESOURCE_CLEAR_FIELDS";