export const FETCH_RESOURCE_BEGIN = "TABLE_FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "TABLE_FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "TABLE_FETCH_RESOURCE_FAILURE";
export const FILTER_RESOURCE = "TABLE_FILTER_RESOURCE";
export const DELETE_RESOURCE_BEGIN = "TABLE_DELETE_RESOURCE_BEGIN";
export const DELETE_RESOURCE_SUCCESS = "TABLE_DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAILURE = "TABLE_DELETE_RESOURCE_FAILURE";
