export const FETCH_RESOURCE_BEGIN = "FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "FETCH_RESOURCE_FAILURE";
export const FILTER_RESOURCE = "FILTER_RESOURCE";
export const DELETE_RESOURCE_BEGIN = "DELETE_RESOURCE_BEGIN";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAILURE = "DELETE_RESOURCE_FAILURE";
