export const FETCH_RESOURCE_BEGIN = "FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "FETCH_RESOURCE_FAILURE";
export const FORM_UPDATE_FIELD = "FORM_UPDATE_FIELD";
export const FORM_SUBMIT_BEGIN = "FORM_SUBMIT_BEGIN";
export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_FAILURE = "FORM_SUBMIT_FAILURE";
