export const FETCH_RESOURCE_BEGIN = "FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "FETCH_RESOURCE_FAILURE";
export const FORM_UPDATE_FIELD = "FORM_UPDATE_FIELD";
