export const FETCH_RESOURCE_BEGIN = "TECHNICIAN_FETCH_RESOURCE_BEGIN";
export const FETCH_RESOURCE_SUCCESS = "TECHNICIAN_FETCH_RESOURCE_SUCCESS";
export const FETCH_RESOURCE_FAILURE = "TECHNICIAN_FETCH_RESOURCE_FAILURE";
export const FORM_SUBMIT_BEGIN = "TECHNICIAN_FORM_SUBMIT_BEGIN";
export const FORM_SUBMIT_SUCCESS = "TECHNICIAN_FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_FAILURE = "TECHNICIAN_FORM_SUBMIT_FAILURE";
